// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file terrabase/backend_type/v1/backend_type.proto (package terrabase.backend_type.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file terrabase/backend_type/v1/backend_type.proto.
 */
export const file_terrabase_backend_type_v1_backend_type: GenFile = /*@__PURE__*/
  fileDesc("Cix0ZXJyYWJhc2UvYmFja2VuZF90eXBlL3YxL2JhY2tlbmRfdHlwZS5wcm90bxIZdGVycmFiYXNlLmJhY2tlbmRfdHlwZS52MSpACgtCYWNrZW5kVHlwZRIcChhCQUNLRU5EX1RZUEVfVU5TUEVDSUZJRUQQABITCg9CQUNLRU5EX1RZUEVfUzMQAUJSWlBnaXRodWIuY29tL3RlcnJhYmFzZS1kZXYvdGVycmFiYXNlL3NwZWNzL3RlcnJhYmFzZS9iYWNrZW5kX3R5cGUvdjE7YmFja2VuZFR5cGV2MWIGcHJvdG8z");

/**
 * @generated from enum terrabase.backend_type.v1.BackendType
 */
export enum BackendType {
  /**
   * @generated from enum value: BACKEND_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BACKEND_TYPE_S3 = 1;
   */
  S3 = 1,
}

/**
 * Describes the enum terrabase.backend_type.v1.BackendType.
 */
export const BackendTypeSchema: GenEnum<BackendType> = /*@__PURE__*/
  enumDesc(file_terrabase_backend_type_v1_backend_type, 0);

