# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrabase.state_version.v1 import state_version_pb2 as terrabase_dot_state__version_dot_v1_dot_state__version__pb2


class StateVersionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStateVersion = channel.unary_unary(
                '/terrabase.state_version.v1.StateVersionService/CreateStateVersion',
                request_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionRequest.SerializeToString,
                response_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionResponse.FromString,
                _registered_method=True)
        self.GetStateVersion = channel.unary_unary(
                '/terrabase.state_version.v1.StateVersionService/GetStateVersion',
                request_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionRequest.SerializeToString,
                response_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionResponse.FromString,
                _registered_method=True)
        self.ListStateVersions = channel.unary_unary(
                '/terrabase.state_version.v1.StateVersionService/ListStateVersions',
                request_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsRequest.SerializeToString,
                response_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsResponse.FromString,
                _registered_method=True)
        self.DeleteStateVersion = channel.unary_unary(
                '/terrabase.state_version.v1.StateVersionService/DeleteStateVersion',
                request_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionRequest.SerializeToString,
                response_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionResponse.FromString,
                _registered_method=True)


class StateVersionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateStateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStateVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStateVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateVersionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStateVersion,
                    request_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionRequest.FromString,
                    response_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionResponse.SerializeToString,
            ),
            'GetStateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateVersion,
                    request_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionRequest.FromString,
                    response_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionResponse.SerializeToString,
            ),
            'ListStateVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStateVersions,
                    request_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsRequest.FromString,
                    response_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsResponse.SerializeToString,
            ),
            'DeleteStateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStateVersion,
                    request_deserializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionRequest.FromString,
                    response_serializer=terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terrabase.state_version.v1.StateVersionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terrabase.state_version.v1.StateVersionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateVersionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateStateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.state_version.v1.StateVersionService/CreateStateVersion',
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionRequest.SerializeToString,
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.CreateStateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.state_version.v1.StateVersionService/GetStateVersion',
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionRequest.SerializeToString,
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.GetStateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStateVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.state_version.v1.StateVersionService/ListStateVersions',
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsRequest.SerializeToString,
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.ListStateVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.state_version.v1.StateVersionService/DeleteStateVersion',
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionRequest.SerializeToString,
            terrabase_dot_state__version_dot_v1_dot_state__version__pb2.DeleteStateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
