// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: terrabase/workspace/v1/workspace.proto

package workspacev1

import (
	v1 "github.com/terrabase-dev/terrabase/specs/terrabase/backend_type/v1"
	v11 "github.com/terrabase-dev/terrabase/specs/terrabase/s3_backend_config/v1"
	v12 "github.com/terrabase-dev/terrabase/specs/terrabase/team/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BackendType       v1.BackendType         `protobuf:"varint,3,opt,name=backend_type,json=backendType,proto3,enum=terrabase.backend_type.v1.BackendType" json:"backend_type,omitempty"`
	EnvironmentId     *string                `protobuf:"bytes,4,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	S3BackendConfigId *string                `protobuf:"bytes,5,opt,name=s3_backend_config_id,json=s3BackendConfigId,proto3,oneof" json:"s3_backend_config_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetBackendType() v1.BackendType {
	if x != nil {
		return x.BackendType
	}
	return v1.BackendType(0)
}

func (x *Workspace) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

func (x *Workspace) GetS3BackendConfigId() string {
	if x != nil && x.S3BackendConfigId != nil {
		return *x.S3BackendConfigId
	}
	return ""
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateWorkspaceRequest struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	Name            string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BackendType     v1.BackendType                    `protobuf:"varint,2,opt,name=backend_type,json=backendType,proto3,enum=terrabase.backend_type.v1.BackendType" json:"backend_type,omitempty"`
	EnvironmentId   *string                           `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	TeamId          *string                           `protobuf:"bytes,4,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	S3BackendConfig *v11.CreateS3BackendConfigRequest `protobuf:"bytes,5,opt,name=s3_backend_config,json=s3BackendConfig,proto3" json:"s3_backend_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetBackendType() v1.BackendType {
	if x != nil {
		return x.BackendType
	}
	return v1.BackendType(0)
}

func (x *CreateWorkspaceRequest) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetS3BackendConfig() *v11.CreateS3BackendConfigRequest {
	if x != nil {
		return x.S3BackendConfig
	}
	return nil
}

type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceResponse) Reset() {
	*x = GetWorkspaceResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceResponse) ProtoMessage() {}

func (x *GetWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	TeamId        *string                `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	EnvironmentId *string                `protobuf:"bytes,4,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkspacesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListWorkspacesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListWorkspacesRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *ListWorkspacesRequest) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListWorkspacesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateWorkspaceRequest struct {
	state             protoimpl.MessageState            `protogen:"open.v1"`
	Id                string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              *string                           `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BackendType       v1.BackendType                    `protobuf:"varint,3,opt,name=backend_type,json=backendType,proto3,enum=terrabase.backend_type.v1.BackendType" json:"backend_type,omitempty"`
	EnvironmentId     *string                           `protobuf:"bytes,4,opt,name=environment_id,json=environmentId,proto3,oneof" json:"environment_id,omitempty"`
	TeamId            *string                           `protobuf:"bytes,5,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	S3BackendConfigId *string                           `protobuf:"bytes,6,opt,name=s3_backend_config_id,json=s3BackendConfigId,proto3,oneof" json:"s3_backend_config_id,omitempty"`
	S3BackendConfig   *v11.CreateS3BackendConfigRequest `protobuf:"bytes,7,opt,name=s3_backend_config,json=s3BackendConfig,proto3" json:"s3_backend_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetBackendType() v1.BackendType {
	if x != nil {
		return x.BackendType
	}
	return v1.BackendType(0)
}

func (x *UpdateWorkspaceRequest) GetEnvironmentId() string {
	if x != nil && x.EnvironmentId != nil {
		return *x.EnvironmentId
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetS3BackendConfigId() string {
	if x != nil && x.S3BackendConfigId != nil {
		return *x.S3BackendConfigId
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetS3BackendConfig() *v11.CreateS3BackendConfigRequest {
	if x != nil {
		return x.S3BackendConfig
	}
	return nil
}

type UpdateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceResponse) Reset() {
	*x = UpdateWorkspaceResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceResponse) ProtoMessage() {}

func (x *UpdateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{10}
}

type GrantTeamAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TeamIds       *v12.TeamIds           `protobuf:"bytes,2,opt,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTeamAccessRequest) Reset() {
	*x = GrantTeamAccessRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessRequest) ProtoMessage() {}

func (x *GrantTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *GrantTeamAccessRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GrantTeamAccessRequest) GetTeamIds() *v12.TeamIds {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type GrantTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTeamAccessResponse) Reset() {
	*x = GrantTeamAccessResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessResponse) ProtoMessage() {}

func (x *GrantTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{12}
}

type RevokeTeamAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TeamIds       *v12.TeamIds           `protobuf:"bytes,2,opt,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessRequest) Reset() {
	*x = RevokeTeamAccessRequest{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessRequest) ProtoMessage() {}

func (x *RevokeTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeTeamAccessRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RevokeTeamAccessRequest) GetTeamIds() *v12.TeamIds {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type RevokeTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessResponse) Reset() {
	*x = RevokeTeamAccessResponse{}
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessResponse) ProtoMessage() {}

func (x *RevokeTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_workspace_v1_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_workspace_v1_workspace_proto_rawDescGZIP(), []int{14}
}

var File_terrabase_workspace_v1_workspace_proto protoreflect.FileDescriptor

const file_terrabase_workspace_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"&terrabase/workspace/v1/workspace.proto\x12\x16terrabase.workspace.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,terrabase/backend_type/v1/backend_type.proto\x1a6terrabase/s3_backend_config/v1/s3_backend_config.proto\x1a\x1cterrabase/team/v1/team.proto\"\xfe\x02\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\fbackend_type\x18\x03 \x01(\x0e2&.terrabase.backend_type.v1.BackendTypeR\vbackendType\x12*\n" +
	"\x0eenvironment_id\x18\x04 \x01(\tH\x00R\renvironmentId\x88\x01\x01\x124\n" +
	"\x14s3_backend_config_id\x18\x05 \x01(\tH\x01R\x11s3BackendConfigId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x11\n" +
	"\x0f_environment_idB\x17\n" +
	"\x15_s3_backend_config_id\"\xd4\x02\n" +
	"\x16CreateWorkspaceRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12N\n" +
	"\fbackend_type\x18\x02 \x01(\x0e2&.terrabase.backend_type.v1.BackendTypeB\x03\xe0A\x02R\vbackendType\x12*\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tH\x00R\renvironmentId\x88\x01\x01\x12\x1c\n" +
	"\ateam_id\x18\x04 \x01(\tH\x01R\x06teamId\x88\x01\x01\x12h\n" +
	"\x11s3_backend_config\x18\x05 \x01(\v2<.terrabase.s3_backend_config.v1.CreateS3BackendConfigRequestR\x0fs3BackendConfigB\x11\n" +
	"\x0f_environment_idB\n" +
	"\n" +
	"\b_team_id\"Z\n" +
	"\x17CreateWorkspaceResponse\x12?\n" +
	"\tworkspace\x18\x01 \x01(\v2!.terrabase.workspace.v1.WorkspaceR\tworkspace\"*\n" +
	"\x13GetWorkspaceRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"W\n" +
	"\x14GetWorkspaceResponse\x12?\n" +
	"\tworkspace\x18\x01 \x01(\v2!.terrabase.workspace.v1.WorkspaceR\tworkspace\"\xe3\x01\n" +
	"\x15ListWorkspacesRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01\x12\x1c\n" +
	"\ateam_id\x18\x03 \x01(\tH\x02R\x06teamId\x88\x01\x01\x12*\n" +
	"\x0eenvironment_id\x18\x04 \x01(\tH\x03R\renvironmentId\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\n" +
	"\n" +
	"\b_team_idB\x11\n" +
	"\x0f_environment_id\"\x9c\x01\n" +
	"\x16ListWorkspacesResponse\x12A\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2!.terrabase.workspace.v1.WorkspaceR\n" +
	"workspaces\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xbc\x03\n" +
	"\x16UpdateWorkspaceRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12I\n" +
	"\fbackend_type\x18\x03 \x01(\x0e2&.terrabase.backend_type.v1.BackendTypeR\vbackendType\x12*\n" +
	"\x0eenvironment_id\x18\x04 \x01(\tH\x01R\renvironmentId\x88\x01\x01\x12\x1c\n" +
	"\ateam_id\x18\x05 \x01(\tH\x02R\x06teamId\x88\x01\x01\x124\n" +
	"\x14s3_backend_config_id\x18\x06 \x01(\tH\x03R\x11s3BackendConfigId\x88\x01\x01\x12h\n" +
	"\x11s3_backend_config\x18\a \x01(\v2<.terrabase.s3_backend_config.v1.CreateS3BackendConfigRequestR\x0fs3BackendConfigB\a\n" +
	"\x05_nameB\x11\n" +
	"\x0f_environment_idB\n" +
	"\n" +
	"\b_team_idB\x17\n" +
	"\x15_s3_backend_config_id\"Z\n" +
	"\x17UpdateWorkspaceResponse\x12?\n" +
	"\tworkspace\x18\x01 \x01(\v2!.terrabase.workspace.v1.WorkspaceR\tworkspace\"-\n" +
	"\x16DeleteWorkspaceRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x19\n" +
	"\x17DeleteWorkspaceResponse\"|\n" +
	"\x16GrantTeamAccessRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12:\n" +
	"\bteam_ids\x18\x02 \x01(\v2\x1a.terrabase.team.v1.TeamIdsB\x03\xe0A\x02R\ateamIds\"\x19\n" +
	"\x17GrantTeamAccessResponse\"}\n" +
	"\x17RevokeTeamAccessRequest\x12&\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12:\n" +
	"\bteam_ids\x18\x02 \x01(\v2\x1a.terrabase.team.v1.TeamIdsB\x03\xe0A\x02R\ateamIds\"\x1a\n" +
	"\x18RevokeTeamAccessResponse2\xb5\x06\n" +
	"\x10WorkspaceService\x12r\n" +
	"\x0fCreateWorkspace\x12..terrabase.workspace.v1.CreateWorkspaceRequest\x1a/.terrabase.workspace.v1.CreateWorkspaceResponse\x12i\n" +
	"\fGetWorkspace\x12+.terrabase.workspace.v1.GetWorkspaceRequest\x1a,.terrabase.workspace.v1.GetWorkspaceResponse\x12o\n" +
	"\x0eListWorkspaces\x12-.terrabase.workspace.v1.ListWorkspacesRequest\x1a..terrabase.workspace.v1.ListWorkspacesResponse\x12r\n" +
	"\x0fUpdateWorkspace\x12..terrabase.workspace.v1.UpdateWorkspaceRequest\x1a/.terrabase.workspace.v1.UpdateWorkspaceResponse\x12r\n" +
	"\x0fDeleteWorkspace\x12..terrabase.workspace.v1.DeleteWorkspaceRequest\x1a/.terrabase.workspace.v1.DeleteWorkspaceResponse\x12r\n" +
	"\x0fGrantTeamAccess\x12..terrabase.workspace.v1.GrantTeamAccessRequest\x1a/.terrabase.workspace.v1.GrantTeamAccessResponse\x12u\n" +
	"\x10RevokeTeamAccess\x12/.terrabase.workspace.v1.RevokeTeamAccessRequest\x1a0.terrabase.workspace.v1.RevokeTeamAccessResponseBMZKgithub.com/terrabase-dev/terrabase/specs/terrabase/workspace/v1;workspacev1b\x06proto3"

var (
	file_terrabase_workspace_v1_workspace_proto_rawDescOnce sync.Once
	file_terrabase_workspace_v1_workspace_proto_rawDescData []byte
)

func file_terrabase_workspace_v1_workspace_proto_rawDescGZIP() []byte {
	file_terrabase_workspace_v1_workspace_proto_rawDescOnce.Do(func() {
		file_terrabase_workspace_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrabase_workspace_v1_workspace_proto_rawDesc), len(file_terrabase_workspace_v1_workspace_proto_rawDesc)))
	})
	return file_terrabase_workspace_v1_workspace_proto_rawDescData
}

var file_terrabase_workspace_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_terrabase_workspace_v1_workspace_proto_goTypes = []any{
	(*Workspace)(nil),                        // 0: terrabase.workspace.v1.Workspace
	(*CreateWorkspaceRequest)(nil),           // 1: terrabase.workspace.v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil),          // 2: terrabase.workspace.v1.CreateWorkspaceResponse
	(*GetWorkspaceRequest)(nil),              // 3: terrabase.workspace.v1.GetWorkspaceRequest
	(*GetWorkspaceResponse)(nil),             // 4: terrabase.workspace.v1.GetWorkspaceResponse
	(*ListWorkspacesRequest)(nil),            // 5: terrabase.workspace.v1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),           // 6: terrabase.workspace.v1.ListWorkspacesResponse
	(*UpdateWorkspaceRequest)(nil),           // 7: terrabase.workspace.v1.UpdateWorkspaceRequest
	(*UpdateWorkspaceResponse)(nil),          // 8: terrabase.workspace.v1.UpdateWorkspaceResponse
	(*DeleteWorkspaceRequest)(nil),           // 9: terrabase.workspace.v1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil),          // 10: terrabase.workspace.v1.DeleteWorkspaceResponse
	(*GrantTeamAccessRequest)(nil),           // 11: terrabase.workspace.v1.GrantTeamAccessRequest
	(*GrantTeamAccessResponse)(nil),          // 12: terrabase.workspace.v1.GrantTeamAccessResponse
	(*RevokeTeamAccessRequest)(nil),          // 13: terrabase.workspace.v1.RevokeTeamAccessRequest
	(*RevokeTeamAccessResponse)(nil),         // 14: terrabase.workspace.v1.RevokeTeamAccessResponse
	(v1.BackendType)(0),                      // 15: terrabase.backend_type.v1.BackendType
	(*timestamppb.Timestamp)(nil),            // 16: google.protobuf.Timestamp
	(*v11.CreateS3BackendConfigRequest)(nil), // 17: terrabase.s3_backend_config.v1.CreateS3BackendConfigRequest
	(*v12.TeamIds)(nil),                      // 18: terrabase.team.v1.TeamIds
}
var file_terrabase_workspace_v1_workspace_proto_depIdxs = []int32{
	15, // 0: terrabase.workspace.v1.Workspace.backend_type:type_name -> terrabase.backend_type.v1.BackendType
	16, // 1: terrabase.workspace.v1.Workspace.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: terrabase.workspace.v1.Workspace.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: terrabase.workspace.v1.CreateWorkspaceRequest.backend_type:type_name -> terrabase.backend_type.v1.BackendType
	17, // 4: terrabase.workspace.v1.CreateWorkspaceRequest.s3_backend_config:type_name -> terrabase.s3_backend_config.v1.CreateS3BackendConfigRequest
	0,  // 5: terrabase.workspace.v1.CreateWorkspaceResponse.workspace:type_name -> terrabase.workspace.v1.Workspace
	0,  // 6: terrabase.workspace.v1.GetWorkspaceResponse.workspace:type_name -> terrabase.workspace.v1.Workspace
	0,  // 7: terrabase.workspace.v1.ListWorkspacesResponse.workspaces:type_name -> terrabase.workspace.v1.Workspace
	15, // 8: terrabase.workspace.v1.UpdateWorkspaceRequest.backend_type:type_name -> terrabase.backend_type.v1.BackendType
	17, // 9: terrabase.workspace.v1.UpdateWorkspaceRequest.s3_backend_config:type_name -> terrabase.s3_backend_config.v1.CreateS3BackendConfigRequest
	0,  // 10: terrabase.workspace.v1.UpdateWorkspaceResponse.workspace:type_name -> terrabase.workspace.v1.Workspace
	18, // 11: terrabase.workspace.v1.GrantTeamAccessRequest.team_ids:type_name -> terrabase.team.v1.TeamIds
	18, // 12: terrabase.workspace.v1.RevokeTeamAccessRequest.team_ids:type_name -> terrabase.team.v1.TeamIds
	1,  // 13: terrabase.workspace.v1.WorkspaceService.CreateWorkspace:input_type -> terrabase.workspace.v1.CreateWorkspaceRequest
	3,  // 14: terrabase.workspace.v1.WorkspaceService.GetWorkspace:input_type -> terrabase.workspace.v1.GetWorkspaceRequest
	5,  // 15: terrabase.workspace.v1.WorkspaceService.ListWorkspaces:input_type -> terrabase.workspace.v1.ListWorkspacesRequest
	7,  // 16: terrabase.workspace.v1.WorkspaceService.UpdateWorkspace:input_type -> terrabase.workspace.v1.UpdateWorkspaceRequest
	9,  // 17: terrabase.workspace.v1.WorkspaceService.DeleteWorkspace:input_type -> terrabase.workspace.v1.DeleteWorkspaceRequest
	11, // 18: terrabase.workspace.v1.WorkspaceService.GrantTeamAccess:input_type -> terrabase.workspace.v1.GrantTeamAccessRequest
	13, // 19: terrabase.workspace.v1.WorkspaceService.RevokeTeamAccess:input_type -> terrabase.workspace.v1.RevokeTeamAccessRequest
	2,  // 20: terrabase.workspace.v1.WorkspaceService.CreateWorkspace:output_type -> terrabase.workspace.v1.CreateWorkspaceResponse
	4,  // 21: terrabase.workspace.v1.WorkspaceService.GetWorkspace:output_type -> terrabase.workspace.v1.GetWorkspaceResponse
	6,  // 22: terrabase.workspace.v1.WorkspaceService.ListWorkspaces:output_type -> terrabase.workspace.v1.ListWorkspacesResponse
	8,  // 23: terrabase.workspace.v1.WorkspaceService.UpdateWorkspace:output_type -> terrabase.workspace.v1.UpdateWorkspaceResponse
	10, // 24: terrabase.workspace.v1.WorkspaceService.DeleteWorkspace:output_type -> terrabase.workspace.v1.DeleteWorkspaceResponse
	12, // 25: terrabase.workspace.v1.WorkspaceService.GrantTeamAccess:output_type -> terrabase.workspace.v1.GrantTeamAccessResponse
	14, // 26: terrabase.workspace.v1.WorkspaceService.RevokeTeamAccess:output_type -> terrabase.workspace.v1.RevokeTeamAccessResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_terrabase_workspace_v1_workspace_proto_init() }
func file_terrabase_workspace_v1_workspace_proto_init() {
	if File_terrabase_workspace_v1_workspace_proto != nil {
		return
	}
	file_terrabase_workspace_v1_workspace_proto_msgTypes[0].OneofWrappers = []any{}
	file_terrabase_workspace_v1_workspace_proto_msgTypes[1].OneofWrappers = []any{}
	file_terrabase_workspace_v1_workspace_proto_msgTypes[5].OneofWrappers = []any{}
	file_terrabase_workspace_v1_workspace_proto_msgTypes[6].OneofWrappers = []any{}
	file_terrabase_workspace_v1_workspace_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrabase_workspace_v1_workspace_proto_rawDesc), len(file_terrabase_workspace_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terrabase_workspace_v1_workspace_proto_goTypes,
		DependencyIndexes: file_terrabase_workspace_v1_workspace_proto_depIdxs,
		MessageInfos:      file_terrabase_workspace_v1_workspace_proto_msgTypes,
	}.Build()
	File_terrabase_workspace_v1_workspace_proto = out.File
	file_terrabase_workspace_v1_workspace_proto_goTypes = nil
	file_terrabase_workspace_v1_workspace_proto_depIdxs = nil
}
