// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: terrabase/organization/v1/organization.proto

package organizationv1

import (
	_ "github.com/terrabase-dev/terrabase/specs/terrabase/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription int32

const (
	Subscription_SUBSCRIPTION_UNSPECIFIED Subscription = 0
	Subscription_SUBSCRIPTION_FREE        Subscription = 1
	Subscription_SUBSCRIPTION_TEAM        Subscription = 2
	Subscription_SUBSCRIPTION_ENTERPRISE  Subscription = 3
)

// Enum value maps for Subscription.
var (
	Subscription_name = map[int32]string{
		0: "SUBSCRIPTION_UNSPECIFIED",
		1: "SUBSCRIPTION_FREE",
		2: "SUBSCRIPTION_TEAM",
		3: "SUBSCRIPTION_ENTERPRISE",
	}
	Subscription_value = map[string]int32{
		"SUBSCRIPTION_UNSPECIFIED": 0,
		"SUBSCRIPTION_FREE":        1,
		"SUBSCRIPTION_TEAM":        2,
		"SUBSCRIPTION_ENTERPRISE":  3,
	}
)

func (x Subscription) Enum() *Subscription {
	p := new(Subscription)
	*p = x
	return p
}

func (x Subscription) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subscription) Descriptor() protoreflect.EnumDescriptor {
	return file_terrabase_organization_v1_organization_proto_enumTypes[0].Descriptor()
}

func (Subscription) Type() protoreflect.EnumType {
	return &file_terrabase_organization_v1_organization_proto_enumTypes[0]
}

func (x Subscription) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subscription.Descriptor instead.
func (Subscription) EnumDescriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{0}
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subscription  Subscription           `protobuf:"varint,3,opt,name=subscription,proto3,enum=terrabase.organization.v1.Subscription" json:"subscription,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetSubscription() Subscription {
	if x != nil {
		return x.Subscription
	}
	return Subscription_SUBSCRIPTION_UNSPECIFIED
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subscription  Subscription           `protobuf:"varint,2,opt,name=subscription,proto3,enum=terrabase.organization.v1.Subscription" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSubscription() Subscription {
	if x != nil {
		return x.Subscription
	}
	return Subscription_SUBSCRIPTION_UNSPECIFIED
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrganizationsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOrganizationsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Subscription  *Subscription          `protobuf:"varint,3,opt,name=subscription,proto3,enum=terrabase.organization.v1.Subscription,oneof" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetSubscription() Subscription {
	if x != nil && x.Subscription != nil {
		return *x.Subscription
	}
	return Subscription_SUBSCRIPTION_UNSPECIFIED
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrganizationResponse) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResponse) Reset() {
	*x = DeleteOrganizationResponse{}
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResponse) ProtoMessage() {}

func (x *DeleteOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_organization_v1_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_organization_v1_organization_proto_rawDescGZIP(), []int{10}
}

var File_terrabase_organization_v1_organization_proto protoreflect.FileDescriptor

const file_terrabase_organization_v1_organization_proto_rawDesc = "" +
	"\n" +
	",terrabase/organization/v1/organization.proto\x12\x19terrabase.organization.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eterrabase/authz/v1/authz.proto\"\xf5\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12K\n" +
	"\fsubscription\x18\x03 \x01(\x0e2'.terrabase.organization.v1.SubscriptionR\fsubscription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x01\n" +
	"\x19CreateOrganizationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12P\n" +
	"\fsubscription\x18\x02 \x01(\x0e2'.terrabase.organization.v1.SubscriptionB\x03\xe0A\x02R\fsubscription\"i\n" +
	"\x1aCreateOrganizationResponse\x12K\n" +
	"\forganization\x18\x01 \x01(\v2'.terrabase.organization.v1.OrganizationR\forganization\"-\n" +
	"\x16GetOrganizationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"f\n" +
	"\x17GetOrganizationResponse\x12K\n" +
	"\forganization\x18\x01 \x01(\v2'.terrabase.organization.v1.OrganizationR\forganization\"}\n" +
	"\x18ListOrganizationsRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xab\x01\n" +
	"\x19ListOrganizationsResponse\x12M\n" +
	"\rorganizations\x18\x01 \x03(\v2'.terrabase.organization.v1.OrganizationR\rorganizations\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xb5\x01\n" +
	"\x19UpdateOrganizationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12P\n" +
	"\fsubscription\x18\x03 \x01(\x0e2'.terrabase.organization.v1.SubscriptionH\x01R\fsubscription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_subscription\"i\n" +
	"\x1aUpdateOrganizationResponse\x12K\n" +
	"\forganization\x18\x01 \x01(\v2'.terrabase.organization.v1.OrganizationR\forganization\"0\n" +
	"\x19DeleteOrganizationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x1c\n" +
	"\x1aDeleteOrganizationResponse*w\n" +
	"\fSubscription\x12\x1c\n" +
	"\x18SUBSCRIPTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SUBSCRIPTION_FREE\x10\x01\x12\x15\n" +
	"\x11SUBSCRIPTION_TEAM\x10\x02\x12\x1b\n" +
	"\x17SUBSCRIPTION_ENTERPRISE\x10\x032\x9e\a\n" +
	"\x13OrganizationService\x12\xb4\x01\n" +
	"\x12CreateOrganization\x124.terrabase.organization.v1.CreateOrganizationRequest\x1a5.terrabase.organization.v1.CreateOrganizationResponse\"1\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x9a\xb5\x18\x0fUnauthenticated\x9a\xb5\x18\x10PermissionDenied\x12\xac\x01\n" +
	"\x0fGetOrganization\x121.terrabase.organization.v1.GetOrganizationRequest\x1a2.terrabase.organization.v1.GetOrganizationResponse\"2\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x03\x02\x9a\xb5\x18\x0fUnauthenticated\x9a\xb5\x18\x10PermissionDenied\x12\xb2\x01\n" +
	"\x11ListOrganizations\x123.terrabase.organization.v1.ListOrganizationsRequest\x1a4.terrabase.organization.v1.ListOrganizationsResponse\"2\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\x03\x02\x9a\xb5\x18\x0fUnauthenticated\x9a\xb5\x18\x10PermissionDenied\x12\xb4\x01\n" +
	"\x12UpdateOrganization\x124.terrabase.organization.v1.UpdateOrganizationRequest\x1a5.terrabase.organization.v1.UpdateOrganizationResponse\"1\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x9a\xb5\x18\x0fUnauthenticated\x9a\xb5\x18\x10PermissionDenied\x12\xb4\x01\n" +
	"\x12DeleteOrganization\x124.terrabase.organization.v1.DeleteOrganizationRequest\x1a5.terrabase.organization.v1.DeleteOrganizationResponse\"1\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x02\x9a\xb5\x18\x0fUnauthenticated\x9a\xb5\x18\x10PermissionDeniedBSZQgithub.com/terrabase-dev/terrabase/specs/terrabase/organization/v1;organizationv1b\x06proto3"

var (
	file_terrabase_organization_v1_organization_proto_rawDescOnce sync.Once
	file_terrabase_organization_v1_organization_proto_rawDescData []byte
)

func file_terrabase_organization_v1_organization_proto_rawDescGZIP() []byte {
	file_terrabase_organization_v1_organization_proto_rawDescOnce.Do(func() {
		file_terrabase_organization_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrabase_organization_v1_organization_proto_rawDesc), len(file_terrabase_organization_v1_organization_proto_rawDesc)))
	})
	return file_terrabase_organization_v1_organization_proto_rawDescData
}

var file_terrabase_organization_v1_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_terrabase_organization_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_terrabase_organization_v1_organization_proto_goTypes = []any{
	(Subscription)(0),                  // 0: terrabase.organization.v1.Subscription
	(*Organization)(nil),               // 1: terrabase.organization.v1.Organization
	(*CreateOrganizationRequest)(nil),  // 2: terrabase.organization.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil), // 3: terrabase.organization.v1.CreateOrganizationResponse
	(*GetOrganizationRequest)(nil),     // 4: terrabase.organization.v1.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),    // 5: terrabase.organization.v1.GetOrganizationResponse
	(*ListOrganizationsRequest)(nil),   // 6: terrabase.organization.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),  // 7: terrabase.organization.v1.ListOrganizationsResponse
	(*UpdateOrganizationRequest)(nil),  // 8: terrabase.organization.v1.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil), // 9: terrabase.organization.v1.UpdateOrganizationResponse
	(*DeleteOrganizationRequest)(nil),  // 10: terrabase.organization.v1.DeleteOrganizationRequest
	(*DeleteOrganizationResponse)(nil), // 11: terrabase.organization.v1.DeleteOrganizationResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_terrabase_organization_v1_organization_proto_depIdxs = []int32{
	0,  // 0: terrabase.organization.v1.Organization.subscription:type_name -> terrabase.organization.v1.Subscription
	12, // 1: terrabase.organization.v1.Organization.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: terrabase.organization.v1.Organization.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: terrabase.organization.v1.CreateOrganizationRequest.subscription:type_name -> terrabase.organization.v1.Subscription
	1,  // 4: terrabase.organization.v1.CreateOrganizationResponse.organization:type_name -> terrabase.organization.v1.Organization
	1,  // 5: terrabase.organization.v1.GetOrganizationResponse.organization:type_name -> terrabase.organization.v1.Organization
	1,  // 6: terrabase.organization.v1.ListOrganizationsResponse.organizations:type_name -> terrabase.organization.v1.Organization
	0,  // 7: terrabase.organization.v1.UpdateOrganizationRequest.subscription:type_name -> terrabase.organization.v1.Subscription
	1,  // 8: terrabase.organization.v1.UpdateOrganizationResponse.organization:type_name -> terrabase.organization.v1.Organization
	2,  // 9: terrabase.organization.v1.OrganizationService.CreateOrganization:input_type -> terrabase.organization.v1.CreateOrganizationRequest
	4,  // 10: terrabase.organization.v1.OrganizationService.GetOrganization:input_type -> terrabase.organization.v1.GetOrganizationRequest
	6,  // 11: terrabase.organization.v1.OrganizationService.ListOrganizations:input_type -> terrabase.organization.v1.ListOrganizationsRequest
	8,  // 12: terrabase.organization.v1.OrganizationService.UpdateOrganization:input_type -> terrabase.organization.v1.UpdateOrganizationRequest
	10, // 13: terrabase.organization.v1.OrganizationService.DeleteOrganization:input_type -> terrabase.organization.v1.DeleteOrganizationRequest
	3,  // 14: terrabase.organization.v1.OrganizationService.CreateOrganization:output_type -> terrabase.organization.v1.CreateOrganizationResponse
	5,  // 15: terrabase.organization.v1.OrganizationService.GetOrganization:output_type -> terrabase.organization.v1.GetOrganizationResponse
	7,  // 16: terrabase.organization.v1.OrganizationService.ListOrganizations:output_type -> terrabase.organization.v1.ListOrganizationsResponse
	9,  // 17: terrabase.organization.v1.OrganizationService.UpdateOrganization:output_type -> terrabase.organization.v1.UpdateOrganizationResponse
	11, // 18: terrabase.organization.v1.OrganizationService.DeleteOrganization:output_type -> terrabase.organization.v1.DeleteOrganizationResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_terrabase_organization_v1_organization_proto_init() }
func file_terrabase_organization_v1_organization_proto_init() {
	if File_terrabase_organization_v1_organization_proto != nil {
		return
	}
	file_terrabase_organization_v1_organization_proto_msgTypes[5].OneofWrappers = []any{}
	file_terrabase_organization_v1_organization_proto_msgTypes[6].OneofWrappers = []any{}
	file_terrabase_organization_v1_organization_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrabase_organization_v1_organization_proto_rawDesc), len(file_terrabase_organization_v1_organization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terrabase_organization_v1_organization_proto_goTypes,
		DependencyIndexes: file_terrabase_organization_v1_organization_proto_depIdxs,
		EnumInfos:         file_terrabase_organization_v1_organization_proto_enumTypes,
		MessageInfos:      file_terrabase_organization_v1_organization_proto_msgTypes,
	}.Build()
	File_terrabase_organization_v1_organization_proto = out.File
	file_terrabase_organization_v1_organization_proto_goTypes = nil
	file_terrabase_organization_v1_organization_proto_depIdxs = nil
}
