// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: terrabase/application/v1/application.proto

package applicationv1

import (
	_ "github.com/terrabase-dev/terrabase/specs/terrabase/authz/v1"
	v11 "github.com/terrabase-dev/terrabase/specs/terrabase/team/v1"
	v1 "github.com/terrabase-dev/terrabase/specs/terrabase/team_application_access_grant/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Terrabase application can be deployed in multiple environments, each with their own workspace
type Application struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the application
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The time the application was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time the application was last updated at
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Application) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the application
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ID of the team that owns the application
	TeamId        string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationRequest) Reset() {
	*x = CreateApplicationRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationRequest) ProtoMessage() {}

func (x *CreateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{1}
}

func (x *CreateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApplicationRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type CreateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application that was created
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApplicationResponse) Reset() {
	*x = CreateApplicationResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApplicationResponse) ProtoMessage() {}

func (x *CreateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApplicationResponse.ProtoReflect.Descriptor instead.
func (*CreateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{2}
}

func (x *CreateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type GetApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{3}
}

func (x *GetApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The application
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{4}
}

func (x *GetApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type ListApplicationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a team that owns applications
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The number of applications on each page of results
	PageSize *int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// The token to retrieve the next page of results
	PageToken     *string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{5}
}

func (x *ListApplicationsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListApplicationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of applications
	Applications []*Application `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	// The token to retrieve the next page of results
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{6}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application to update
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new name of the application
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated application
	Application   *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateApplicationResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type DeleteApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteApplicationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{10}
}

type GrantTeamAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of team access grants
	TeamAccessGrants []*v1.CreateTeamApplicationAccessGrantRequest `protobuf:"bytes,1,rep,name=team_access_grants,json=teamAccessGrants,proto3" json:"team_access_grants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrantTeamAccessRequest) Reset() {
	*x = GrantTeamAccessRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessRequest) ProtoMessage() {}

func (x *GrantTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{11}
}

func (x *GrantTeamAccessRequest) GetTeamAccessGrants() []*v1.CreateTeamApplicationAccessGrantRequest {
	if x != nil {
		return x.TeamAccessGrants
	}
	return nil
}

type GrantTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantTeamAccessResponse) Reset() {
	*x = GrantTeamAccessResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantTeamAccessResponse) ProtoMessage() {}

func (x *GrantTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{12}
}

type RevokeTeamAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the application
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// A list of team IDs whose access to the application should be revoked
	TeamIds       *v11.TeamIds `protobuf:"bytes,2,opt,name=team_ids,json=teamIds,proto3" json:"team_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessRequest) Reset() {
	*x = RevokeTeamAccessRequest{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessRequest) ProtoMessage() {}

func (x *RevokeTeamAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeTeamAccessRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RevokeTeamAccessRequest) GetTeamIds() *v11.TeamIds {
	if x != nil {
		return x.TeamIds
	}
	return nil
}

type RevokeTeamAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTeamAccessResponse) Reset() {
	*x = RevokeTeamAccessResponse{}
	mi := &file_terrabase_application_v1_application_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTeamAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTeamAccessResponse) ProtoMessage() {}

func (x *RevokeTeamAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_application_v1_application_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTeamAccessResponse.ProtoReflect.Descriptor instead.
func (*RevokeTeamAccessResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_application_v1_application_proto_rawDescGZIP(), []int{14}
}

var File_terrabase_application_v1_application_proto protoreflect.FileDescriptor

const file_terrabase_application_v1_application_proto_rawDesc = "" +
	"\n" +
	"*terrabase/application/v1/application.proto\x12\x18terrabase.application.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eterrabase/authz/v1/authz.proto\x1a\x1cterrabase/team/v1/team.proto\x1aNterrabase/team_application_access_grant/v1/team_application_access_grant.proto\"\xa7\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\x18CreateApplicationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12\x1c\n" +
	"\ateam_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x06teamId\"d\n" +
	"\x19CreateApplicationResponse\x12G\n" +
	"\vapplication\x18\x01 \x01(\v2%.terrabase.application.v1.ApplicationR\vapplication\",\n" +
	"\x15GetApplicationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"a\n" +
	"\x16GetApplicationResponse\x12G\n" +
	"\vapplication\x18\x01 \x01(\v2%.terrabase.application.v1.ApplicationR\vapplication\"\x9a\x01\n" +
	"\x17ListApplicationsRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xa6\x01\n" +
	"\x18ListApplicationsResponse\x12I\n" +
	"\fapplications\x18\x01 \x03(\v2%.terrabase.application.v1.ApplicationR\fapplications\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"C\n" +
	"\x18UpdateApplicationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"d\n" +
	"\x19UpdateApplicationResponse\x12G\n" +
	"\vapplication\x18\x01 \x01(\v2%.terrabase.application.v1.ApplicationR\vapplication\"/\n" +
	"\x18DeleteApplicationRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x1b\n" +
	"\x19DeleteApplicationResponse\"\xa1\x01\n" +
	"\x16GrantTeamAccessRequest\x12\x86\x01\n" +
	"\x12team_access_grants\x18\x01 \x03(\v2S.terrabase.team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequestB\x03\xe0A\x02R\x10teamAccessGrants\"\x19\n" +
	"\x17GrantTeamAccessResponse\"\x81\x01\n" +
	"\x17RevokeTeamAccessRequest\x12*\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\x03\xe0A\x02R\rapplicationId\x12:\n" +
	"\bteam_ids\x18\x02 \x01(\v2\x1a.terrabase.team.v1.TeamIdsB\x03\xe0A\x02R\ateamIds\"\x1a\n" +
	"\x18RevokeTeamAccessResponse2\xce\a\n" +
	"\x12ApplicationService\x12\x88\x01\n" +
	"\x11CreateApplication\x122.terrabase.application.v1.CreateApplicationRequest\x1a3.terrabase.application.v1.CreateApplicationResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\x12\x80\x01\n" +
	"\x0eGetApplication\x12/.terrabase.application.v1.GetApplicationRequest\x1a0.terrabase.application.v1.GetApplicationResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\a\x06\x12\x86\x01\n" +
	"\x10ListApplications\x121.terrabase.application.v1.ListApplicationsRequest\x1a2.terrabase.application.v1.ListApplicationsResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\a\x06\x12\x88\x01\n" +
	"\x11UpdateApplication\x122.terrabase.application.v1.UpdateApplicationRequest\x1a3.terrabase.application.v1.UpdateApplicationResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\x12\x88\x01\n" +
	"\x11DeleteApplication\x122.terrabase.application.v1.DeleteApplicationRequest\x1a3.terrabase.application.v1.DeleteApplicationResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\x12\x82\x01\n" +
	"\x0fGrantTeamAccess\x120.terrabase.application.v1.GrantTeamAccessRequest\x1a1.terrabase.application.v1.GrantTeamAccessResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06\x12\x85\x01\n" +
	"\x10RevokeTeamAccess\x121.terrabase.application.v1.RevokeTeamAccessRequest\x1a2.terrabase.application.v1.RevokeTeamAccessResponse\"\n" +
	"\x88\xb5\x18\x01\x92\xb5\x18\x02\x01\x06BQZOgithub.com/terrabase-dev/terrabase/specs/terrabase/application/v1;applicationv1b\x06proto3"

var (
	file_terrabase_application_v1_application_proto_rawDescOnce sync.Once
	file_terrabase_application_v1_application_proto_rawDescData []byte
)

func file_terrabase_application_v1_application_proto_rawDescGZIP() []byte {
	file_terrabase_application_v1_application_proto_rawDescOnce.Do(func() {
		file_terrabase_application_v1_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrabase_application_v1_application_proto_rawDesc), len(file_terrabase_application_v1_application_proto_rawDesc)))
	})
	return file_terrabase_application_v1_application_proto_rawDescData
}

var file_terrabase_application_v1_application_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_terrabase_application_v1_application_proto_goTypes = []any{
	(*Application)(nil),                                // 0: terrabase.application.v1.Application
	(*CreateApplicationRequest)(nil),                   // 1: terrabase.application.v1.CreateApplicationRequest
	(*CreateApplicationResponse)(nil),                  // 2: terrabase.application.v1.CreateApplicationResponse
	(*GetApplicationRequest)(nil),                      // 3: terrabase.application.v1.GetApplicationRequest
	(*GetApplicationResponse)(nil),                     // 4: terrabase.application.v1.GetApplicationResponse
	(*ListApplicationsRequest)(nil),                    // 5: terrabase.application.v1.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),                   // 6: terrabase.application.v1.ListApplicationsResponse
	(*UpdateApplicationRequest)(nil),                   // 7: terrabase.application.v1.UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil),                  // 8: terrabase.application.v1.UpdateApplicationResponse
	(*DeleteApplicationRequest)(nil),                   // 9: terrabase.application.v1.DeleteApplicationRequest
	(*DeleteApplicationResponse)(nil),                  // 10: terrabase.application.v1.DeleteApplicationResponse
	(*GrantTeamAccessRequest)(nil),                     // 11: terrabase.application.v1.GrantTeamAccessRequest
	(*GrantTeamAccessResponse)(nil),                    // 12: terrabase.application.v1.GrantTeamAccessResponse
	(*RevokeTeamAccessRequest)(nil),                    // 13: terrabase.application.v1.RevokeTeamAccessRequest
	(*RevokeTeamAccessResponse)(nil),                   // 14: terrabase.application.v1.RevokeTeamAccessResponse
	(*timestamppb.Timestamp)(nil),                      // 15: google.protobuf.Timestamp
	(*v1.CreateTeamApplicationAccessGrantRequest)(nil), // 16: terrabase.team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	(*v11.TeamIds)(nil),                                // 17: terrabase.team.v1.TeamIds
}
var file_terrabase_application_v1_application_proto_depIdxs = []int32{
	15, // 0: terrabase.application.v1.Application.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: terrabase.application.v1.Application.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: terrabase.application.v1.CreateApplicationResponse.application:type_name -> terrabase.application.v1.Application
	0,  // 3: terrabase.application.v1.GetApplicationResponse.application:type_name -> terrabase.application.v1.Application
	0,  // 4: terrabase.application.v1.ListApplicationsResponse.applications:type_name -> terrabase.application.v1.Application
	0,  // 5: terrabase.application.v1.UpdateApplicationResponse.application:type_name -> terrabase.application.v1.Application
	16, // 6: terrabase.application.v1.GrantTeamAccessRequest.team_access_grants:type_name -> terrabase.team_application_access_grant.v1.CreateTeamApplicationAccessGrantRequest
	17, // 7: terrabase.application.v1.RevokeTeamAccessRequest.team_ids:type_name -> terrabase.team.v1.TeamIds
	1,  // 8: terrabase.application.v1.ApplicationService.CreateApplication:input_type -> terrabase.application.v1.CreateApplicationRequest
	3,  // 9: terrabase.application.v1.ApplicationService.GetApplication:input_type -> terrabase.application.v1.GetApplicationRequest
	5,  // 10: terrabase.application.v1.ApplicationService.ListApplications:input_type -> terrabase.application.v1.ListApplicationsRequest
	7,  // 11: terrabase.application.v1.ApplicationService.UpdateApplication:input_type -> terrabase.application.v1.UpdateApplicationRequest
	9,  // 12: terrabase.application.v1.ApplicationService.DeleteApplication:input_type -> terrabase.application.v1.DeleteApplicationRequest
	11, // 13: terrabase.application.v1.ApplicationService.GrantTeamAccess:input_type -> terrabase.application.v1.GrantTeamAccessRequest
	13, // 14: terrabase.application.v1.ApplicationService.RevokeTeamAccess:input_type -> terrabase.application.v1.RevokeTeamAccessRequest
	2,  // 15: terrabase.application.v1.ApplicationService.CreateApplication:output_type -> terrabase.application.v1.CreateApplicationResponse
	4,  // 16: terrabase.application.v1.ApplicationService.GetApplication:output_type -> terrabase.application.v1.GetApplicationResponse
	6,  // 17: terrabase.application.v1.ApplicationService.ListApplications:output_type -> terrabase.application.v1.ListApplicationsResponse
	8,  // 18: terrabase.application.v1.ApplicationService.UpdateApplication:output_type -> terrabase.application.v1.UpdateApplicationResponse
	10, // 19: terrabase.application.v1.ApplicationService.DeleteApplication:output_type -> terrabase.application.v1.DeleteApplicationResponse
	12, // 20: terrabase.application.v1.ApplicationService.GrantTeamAccess:output_type -> terrabase.application.v1.GrantTeamAccessResponse
	14, // 21: terrabase.application.v1.ApplicationService.RevokeTeamAccess:output_type -> terrabase.application.v1.RevokeTeamAccessResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_terrabase_application_v1_application_proto_init() }
func file_terrabase_application_v1_application_proto_init() {
	if File_terrabase_application_v1_application_proto != nil {
		return
	}
	file_terrabase_application_v1_application_proto_msgTypes[5].OneofWrappers = []any{}
	file_terrabase_application_v1_application_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrabase_application_v1_application_proto_rawDesc), len(file_terrabase_application_v1_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terrabase_application_v1_application_proto_goTypes,
		DependencyIndexes: file_terrabase_application_v1_application_proto_depIdxs,
		MessageInfos:      file_terrabase_application_v1_application_proto_msgTypes,
	}.Build()
	File_terrabase_application_v1_application_proto = out.File
	file_terrabase_application_v1_application_proto_goTypes = nil
	file_terrabase_application_v1_application_proto_depIdxs = nil
}
