# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrabase.application.v1 import application_pb2 as terrabase_dot_application_dot_v1_dot_application__pb2


class ApplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateApplication = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/CreateApplication',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationResponse.FromString,
                _registered_method=True)
        self.GetApplication = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/GetApplication',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationResponse.FromString,
                _registered_method=True)
        self.ListApplications = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/ListApplications',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsResponse.FromString,
                _registered_method=True)
        self.UpdateApplication = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/UpdateApplication',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationResponse.FromString,
                _registered_method=True)
        self.DeleteApplication = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/DeleteApplication',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationResponse.FromString,
                _registered_method=True)
        self.GrantTeamAccess = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/GrantTeamAccess',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessResponse.FromString,
                _registered_method=True)
        self.RevokeTeamAccess = channel.unary_unary(
                '/terrabase.application.v1.ApplicationService/RevokeTeamAccess',
                request_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessRequest.SerializeToString,
                response_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessResponse.FromString,
                _registered_method=True)


class ApplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantTeamAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeTeamAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplication,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationResponse.SerializeToString,
            ),
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationResponse.SerializeToString,
            ),
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'UpdateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplication,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationResponse.SerializeToString,
            ),
            'DeleteApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApplication,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationResponse.SerializeToString,
            ),
            'GrantTeamAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantTeamAccess,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessResponse.SerializeToString,
            ),
            'RevokeTeamAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeTeamAccess,
                    request_deserializer=terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessRequest.FromString,
                    response_serializer=terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terrabase.application.v1.ApplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terrabase.application.v1.ApplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/CreateApplication',
            terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.CreateApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/GetApplication',
            terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.GetApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/ListApplications',
            terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.ListApplicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/UpdateApplication',
            terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.UpdateApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/DeleteApplication',
            terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.DeleteApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantTeamAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/GrantTeamAccess',
            terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.GrantTeamAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeTeamAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.application.v1.ApplicationService/RevokeTeamAccess',
            terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessRequest.SerializeToString,
            terrabase_dot_application_dot_v1_dot_application__pb2.RevokeTeamAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
