// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file terrabase/drift_report/v1/drift_report.proto (package terrabase.drift_report.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file terrabase/drift_report/v1/drift_report.proto.
 */
export const file_terrabase_drift_report_v1_drift_report: GenFile = /*@__PURE__*/
  fileDesc("Cix0ZXJyYWJhc2UvZHJpZnRfcmVwb3J0L3YxL2RyaWZ0X3JlcG9ydC5wcm90bxIZdGVycmFiYXNlLmRyaWZ0X3JlcG9ydC52MSKMAQoFRHJpZnQSEwoLcmVzb3VyY2VfaWQYASABKAkSPgoHY2hhbmdlcxgCIAMoCzItLnRlcnJhYmFzZS5kcmlmdF9yZXBvcnQudjEuRHJpZnQuQ2hhbmdlc0VudHJ5Gi4KDENoYW5nZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIqQBCgtEcmlmdFJlcG9ydBIKCgJpZBgBIAEoCRIUCgx3b3Jrc3BhY2VfaWQYAiABKAkSDwoHZHJpZnRlZBgDIAEoCBIxCgdjaGFuZ2VzGAQgAygLMiAudGVycmFiYXNlLmRyaWZ0X3JlcG9ydC52MS5EcmlmdBIvCgtkZXRlY3RlZF9hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAigwEKGENyZWF0ZURyaWZ0UmVwb3J0UmVxdWVzdBIZCgx3b3Jrc3BhY2VfaWQYASABKAlCA+BBAhIUCgdkcmlmdGVkGAIgASgIQgPgQQISNgoHY2hhbmdlcxgDIAMoCzIgLnRlcnJhYmFzZS5kcmlmdF9yZXBvcnQudjEuRHJpZnRCA+BBAiJZChlDcmVhdGVEcmlmdFJlcG9ydFJlc3BvbnNlEjwKDGRyaWZ0X3JlcG9ydBgBIAEoCzImLnRlcnJhYmFzZS5kcmlmdF9yZXBvcnQudjEuRHJpZnRSZXBvcnQiKAoVR2V0RHJpZnRSZXBvcnRSZXF1ZXN0Eg8KAmlkGAEgASgJQgPgQQIiVgoWR2V0RHJpZnRSZXBvcnRSZXNwb25zZRI8CgxkcmlmdF9yZXBvcnQYASABKAsyJi50ZXJyYWJhc2UuZHJpZnRfcmVwb3J0LnYxLkRyaWZ0UmVwb3J0MosCChJEcmlmdFJlcG9ydFNlcnZpY2USfgoRQ3JlYXRlRHJpZnRSZXBvcnQSMy50ZXJyYWJhc2UuZHJpZnRfcmVwb3J0LnYxLkNyZWF0ZURyaWZ0UmVwb3J0UmVxdWVzdBo0LnRlcnJhYmFzZS5kcmlmdF9yZXBvcnQudjEuQ3JlYXRlRHJpZnRSZXBvcnRSZXNwb25zZRJ1Cg5HZXREcmlmdFJlcG9ydBIwLnRlcnJhYmFzZS5kcmlmdF9yZXBvcnQudjEuR2V0RHJpZnRSZXBvcnRSZXF1ZXN0GjEudGVycmFiYXNlLmRyaWZ0X3JlcG9ydC52MS5HZXREcmlmdFJlcG9ydFJlc3BvbnNlQlJaUGdpdGh1Yi5jb20vdGVycmFiYXNlLWRldi90ZXJyYWJhc2Uvc3BlY3MvdGVycmFiYXNlL2RyaWZ0X3JlcG9ydC92MTtkcmlmdFJlcG9ydHYxYgZwcm90bzM", [file_google_api_field_behavior, file_google_protobuf_timestamp]);

/**
 * @generated from message terrabase.drift_report.v1.Drift
 */
export type Drift = Message<"terrabase.drift_report.v1.Drift"> & {
  /**
   * @generated from field: string resource_id = 1;
   */
  resourceId: string;

  /**
   * @generated from field: map<string, string> changes = 2;
   */
  changes: { [key: string]: string };
};

/**
 * Describes the message terrabase.drift_report.v1.Drift.
 * Use `create(DriftSchema)` to create a new message.
 */
export const DriftSchema: GenMessage<Drift> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 0);

/**
 * @generated from message terrabase.drift_report.v1.DriftReport
 */
export type DriftReport = Message<"terrabase.drift_report.v1.DriftReport"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: bool drifted = 3;
   */
  drifted: boolean;

  /**
   * @generated from field: repeated terrabase.drift_report.v1.Drift changes = 4;
   */
  changes: Drift[];

  /**
   * @generated from field: google.protobuf.Timestamp detected_at = 5;
   */
  detectedAt?: Timestamp;
};

/**
 * Describes the message terrabase.drift_report.v1.DriftReport.
 * Use `create(DriftReportSchema)` to create a new message.
 */
export const DriftReportSchema: GenMessage<DriftReport> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 1);

/**
 * @generated from message terrabase.drift_report.v1.CreateDriftReportRequest
 */
export type CreateDriftReportRequest = Message<"terrabase.drift_report.v1.CreateDriftReportRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: bool drifted = 2;
   */
  drifted: boolean;

  /**
   * @generated from field: repeated terrabase.drift_report.v1.Drift changes = 3;
   */
  changes: Drift[];
};

/**
 * Describes the message terrabase.drift_report.v1.CreateDriftReportRequest.
 * Use `create(CreateDriftReportRequestSchema)` to create a new message.
 */
export const CreateDriftReportRequestSchema: GenMessage<CreateDriftReportRequest> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 2);

/**
 * @generated from message terrabase.drift_report.v1.CreateDriftReportResponse
 */
export type CreateDriftReportResponse = Message<"terrabase.drift_report.v1.CreateDriftReportResponse"> & {
  /**
   * @generated from field: terrabase.drift_report.v1.DriftReport drift_report = 1;
   */
  driftReport?: DriftReport;
};

/**
 * Describes the message terrabase.drift_report.v1.CreateDriftReportResponse.
 * Use `create(CreateDriftReportResponseSchema)` to create a new message.
 */
export const CreateDriftReportResponseSchema: GenMessage<CreateDriftReportResponse> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 3);

/**
 * @generated from message terrabase.drift_report.v1.GetDriftReportRequest
 */
export type GetDriftReportRequest = Message<"terrabase.drift_report.v1.GetDriftReportRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message terrabase.drift_report.v1.GetDriftReportRequest.
 * Use `create(GetDriftReportRequestSchema)` to create a new message.
 */
export const GetDriftReportRequestSchema: GenMessage<GetDriftReportRequest> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 4);

/**
 * @generated from message terrabase.drift_report.v1.GetDriftReportResponse
 */
export type GetDriftReportResponse = Message<"terrabase.drift_report.v1.GetDriftReportResponse"> & {
  /**
   * @generated from field: terrabase.drift_report.v1.DriftReport drift_report = 1;
   */
  driftReport?: DriftReport;
};

/**
 * Describes the message terrabase.drift_report.v1.GetDriftReportResponse.
 * Use `create(GetDriftReportResponseSchema)` to create a new message.
 */
export const GetDriftReportResponseSchema: GenMessage<GetDriftReportResponse> = /*@__PURE__*/
  messageDesc(file_terrabase_drift_report_v1_drift_report, 5);

/**
 * @generated from service terrabase.drift_report.v1.DriftReportService
 */
export const DriftReportService: GenService<{
  /**
   * @generated from rpc terrabase.drift_report.v1.DriftReportService.CreateDriftReport
   */
  createDriftReport: {
    methodKind: "unary";
    input: typeof CreateDriftReportRequestSchema;
    output: typeof CreateDriftReportResponseSchema;
  },
  /**
   * @generated from rpc terrabase.drift_report.v1.DriftReportService.GetDriftReport
   */
  getDriftReport: {
    methodKind: "unary";
    input: typeof GetDriftReportRequestSchema;
    output: typeof GetDriftReportResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_terrabase_drift_report_v1_drift_report, 0);

