# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: terrabase/drift_report/v1/drift_report.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'terrabase/drift_report/v1/drift_report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,terrabase/drift_report/v1/drift_report.proto\x12\x19terrabase.drift_report.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n\x05\x44rift\x12\x1f\n\x0bresource_id\x18\x01 \x01(\tR\nresourceId\x12G\n\x07\x63hanges\x18\x02 \x03(\x0b\x32-.terrabase.drift_report.v1.Drift.ChangesEntryR\x07\x63hanges\x1a:\n\x0c\x43hangesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xd3\x01\n\x0b\x44riftReport\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x18\n\x07\x64rifted\x18\x03 \x01(\x08R\x07\x64rifted\x12:\n\x07\x63hanges\x18\x04 \x03(\x0b\x32 .terrabase.drift_report.v1.DriftR\x07\x63hanges\x12;\n\x0b\x64\x65tected_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ndetectedAt\"\xa2\x01\n\x18\x43reateDriftReportRequest\x12&\n\x0cworkspace_id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x0bworkspaceId\x12\x1d\n\x07\x64rifted\x18\x02 \x01(\x08\x42\x03\xe0\x41\x02R\x07\x64rifted\x12?\n\x07\x63hanges\x18\x03 \x03(\x0b\x32 .terrabase.drift_report.v1.DriftB\x03\xe0\x41\x02R\x07\x63hanges\"f\n\x19\x43reateDriftReportResponse\x12I\n\x0c\x64rift_report\x18\x01 \x01(\x0b\x32&.terrabase.drift_report.v1.DriftReportR\x0b\x64riftReport\",\n\x15GetDriftReportRequest\x12\x13\n\x02id\x18\x01 \x01(\tB\x03\xe0\x41\x02R\x02id\"c\n\x16GetDriftReportResponse\x12I\n\x0c\x64rift_report\x18\x01 \x01(\x0b\x32&.terrabase.drift_report.v1.DriftReportR\x0b\x64riftReport2\x8b\x02\n\x12\x44riftReportService\x12~\n\x11\x43reateDriftReport\x12\x33.terrabase.drift_report.v1.CreateDriftReportRequest\x1a\x34.terrabase.drift_report.v1.CreateDriftReportResponse\x12u\n\x0eGetDriftReport\x12\x30.terrabase.drift_report.v1.GetDriftReportRequest\x1a\x31.terrabase.drift_report.v1.GetDriftReportResponseBRZPgithub.com/terrabase-dev/terrabase/specs/terrabase/drift_report/v1;driftReportv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terrabase.drift_report.v1.drift_report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/terrabase-dev/terrabase/specs/terrabase/drift_report/v1;driftReportv1'
  _globals['_DRIFT_CHANGESENTRY']._loaded_options = None
  _globals['_DRIFT_CHANGESENTRY']._serialized_options = b'8\001'
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['workspace_id']._loaded_options = None
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['workspace_id']._serialized_options = b'\340A\002'
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['drifted']._loaded_options = None
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['drifted']._serialized_options = b'\340A\002'
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['changes']._loaded_options = None
  _globals['_CREATEDRIFTREPORTREQUEST'].fields_by_name['changes']._serialized_options = b'\340A\002'
  _globals['_GETDRIFTREPORTREQUEST'].fields_by_name['id']._loaded_options = None
  _globals['_GETDRIFTREPORTREQUEST'].fields_by_name['id']._serialized_options = b'\340A\002'
  _globals['_DRIFT']._serialized_start=142
  _globals['_DRIFT']._serialized_end=315
  _globals['_DRIFT_CHANGESENTRY']._serialized_start=257
  _globals['_DRIFT_CHANGESENTRY']._serialized_end=315
  _globals['_DRIFTREPORT']._serialized_start=318
  _globals['_DRIFTREPORT']._serialized_end=529
  _globals['_CREATEDRIFTREPORTREQUEST']._serialized_start=532
  _globals['_CREATEDRIFTREPORTREQUEST']._serialized_end=694
  _globals['_CREATEDRIFTREPORTRESPONSE']._serialized_start=696
  _globals['_CREATEDRIFTREPORTRESPONSE']._serialized_end=798
  _globals['_GETDRIFTREPORTREQUEST']._serialized_start=800
  _globals['_GETDRIFTREPORTREQUEST']._serialized_end=844
  _globals['_GETDRIFTREPORTRESPONSE']._serialized_start=846
  _globals['_GETDRIFTREPORTRESPONSE']._serialized_end=945
  _globals['_DRIFTREPORTSERVICE']._serialized_start=948
  _globals['_DRIFTREPORTSERVICE']._serialized_end=1215
# @@protoc_insertion_point(module_scope)
