// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: terrabase/team_workspace_access_grant/v1/team_workspace_access_grant.proto

package teamWorkspaceAccessGrantv1

import (
	_ "github.com/terrabase-dev/terrabase/specs/terrabase/authz/v1"
	v1 "github.com/terrabase-dev/terrabase/specs/terrabase/team_access_type/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Grants a team access to a workspace
type TeamWorkspaceAccessGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the team that has access to the workspace
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the workspace the team has access to
	WorkspaceId string `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The type of access the team has to the workspace
	AccessType v1.TeamAccessType `protobuf:"varint,4,opt,name=access_type,json=accessType,proto3,enum=terrabase.team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	// The time the access to the workspace was granted to the team
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time the team's access to the workspaace was last changed
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamWorkspaceAccessGrant) Reset() {
	*x = TeamWorkspaceAccessGrant{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamWorkspaceAccessGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamWorkspaceAccessGrant) ProtoMessage() {}

func (x *TeamWorkspaceAccessGrant) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamWorkspaceAccessGrant.ProtoReflect.Descriptor instead.
func (*TeamWorkspaceAccessGrant) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{0}
}

func (x *TeamWorkspaceAccessGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TeamWorkspaceAccessGrant) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamWorkspaceAccessGrant) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TeamWorkspaceAccessGrant) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

func (x *TeamWorkspaceAccessGrant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TeamWorkspaceAccessGrant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTeamWorkspaceAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the team to grant access to the workspace to
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the workspace to grant the team access to
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The type of access that should be granted to the team
	AccessType    v1.TeamAccessType `protobuf:"varint,3,opt,name=access_type,json=accessType,proto3,enum=terrabase.team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamWorkspaceAccessGrantRequest) Reset() {
	*x = CreateTeamWorkspaceAccessGrantRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamWorkspaceAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamWorkspaceAccessGrantRequest) ProtoMessage() {}

func (x *CreateTeamWorkspaceAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamWorkspaceAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamWorkspaceAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamWorkspaceAccessGrantRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateTeamWorkspaceAccessGrantRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateTeamWorkspaceAccessGrantRequest) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

type CreateTeamWorkspaceAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team access grant that was created
	TeamWorkspaceAccessGrant *TeamWorkspaceAccessGrant `protobuf:"bytes,1,opt,name=team_workspace_access_grant,json=teamWorkspaceAccessGrant,proto3" json:"team_workspace_access_grant,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateTeamWorkspaceAccessGrantResponse) Reset() {
	*x = CreateTeamWorkspaceAccessGrantResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamWorkspaceAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamWorkspaceAccessGrantResponse) ProtoMessage() {}

func (x *CreateTeamWorkspaceAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamWorkspaceAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamWorkspaceAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeamWorkspaceAccessGrantResponse) GetTeamWorkspaceAccessGrant() *TeamWorkspaceAccessGrant {
	if x != nil {
		return x.TeamWorkspaceAccessGrant
	}
	return nil
}

type GetTeamWorkspaceAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamWorkspaceAccessGrantRequest) Reset() {
	*x = GetTeamWorkspaceAccessGrantRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamWorkspaceAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamWorkspaceAccessGrantRequest) ProtoMessage() {}

func (x *GetTeamWorkspaceAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamWorkspaceAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*GetTeamWorkspaceAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeamWorkspaceAccessGrantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTeamWorkspaceAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The team access grant
	TeamWorkspaceAccessGrant *TeamWorkspaceAccessGrant `protobuf:"bytes,1,opt,name=team_workspace_access_grant,json=teamWorkspaceAccessGrant,proto3" json:"team_workspace_access_grant,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetTeamWorkspaceAccessGrantResponse) Reset() {
	*x = GetTeamWorkspaceAccessGrantResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamWorkspaceAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamWorkspaceAccessGrantResponse) ProtoMessage() {}

func (x *GetTeamWorkspaceAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamWorkspaceAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*GetTeamWorkspaceAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamWorkspaceAccessGrantResponse) GetTeamWorkspaceAccessGrant() *TeamWorkspaceAccessGrant {
	if x != nil {
		return x.TeamWorkspaceAccessGrant
	}
	return nil
}

type ListTeamWorkspaceAccessGrantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of a team to list all workspaces that the team has access to
	TeamId *string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3,oneof" json:"team_id,omitempty"`
	// The ID of an workspace to list all the teams that have access to it
	WorkspaceId *string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3,oneof" json:"workspace_id,omitempty"`
	// The number of access grants on each page of results
	PageSize *int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// The token to retrieve the next page of results
	PageToken     *string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamWorkspaceAccessGrantsRequest) Reset() {
	*x = ListTeamWorkspaceAccessGrantsRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamWorkspaceAccessGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamWorkspaceAccessGrantsRequest) ProtoMessage() {}

func (x *ListTeamWorkspaceAccessGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamWorkspaceAccessGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamWorkspaceAccessGrantsRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeamWorkspaceAccessGrantsRequest) GetTeamId() string {
	if x != nil && x.TeamId != nil {
		return *x.TeamId
	}
	return ""
}

func (x *ListTeamWorkspaceAccessGrantsRequest) GetWorkspaceId() string {
	if x != nil && x.WorkspaceId != nil {
		return *x.WorkspaceId
	}
	return ""
}

func (x *ListTeamWorkspaceAccessGrantsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListTeamWorkspaceAccessGrantsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListTeamWorkspaceAccessGrantsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of team access grants
	TeamWorkspaceAccessGrants []*TeamWorkspaceAccessGrant `protobuf:"bytes,1,rep,name=team_workspace_access_grants,json=teamWorkspaceAccessGrants,proto3" json:"team_workspace_access_grants,omitempty"`
	// The token to retrieve the next page of results
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamWorkspaceAccessGrantsResponse) Reset() {
	*x = ListTeamWorkspaceAccessGrantsResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamWorkspaceAccessGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamWorkspaceAccessGrantsResponse) ProtoMessage() {}

func (x *ListTeamWorkspaceAccessGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamWorkspaceAccessGrantsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamWorkspaceAccessGrantsResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{6}
}

func (x *ListTeamWorkspaceAccessGrantsResponse) GetTeamWorkspaceAccessGrants() []*TeamWorkspaceAccessGrant {
	if x != nil {
		return x.TeamWorkspaceAccessGrants
	}
	return nil
}

func (x *ListTeamWorkspaceAccessGrantsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type UpdateTeamWorkspaceAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The new type of access that should be granted to the team
	AccessType    v1.TeamAccessType `protobuf:"varint,2,opt,name=access_type,json=accessType,proto3,enum=terrabase.team_access_type.v1.TeamAccessType" json:"access_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamWorkspaceAccessGrantRequest) Reset() {
	*x = UpdateTeamWorkspaceAccessGrantRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamWorkspaceAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamWorkspaceAccessGrantRequest) ProtoMessage() {}

func (x *UpdateTeamWorkspaceAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamWorkspaceAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamWorkspaceAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTeamWorkspaceAccessGrantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTeamWorkspaceAccessGrantRequest) GetAccessType() v1.TeamAccessType {
	if x != nil {
		return x.AccessType
	}
	return v1.TeamAccessType(0)
}

type UpdateTeamWorkspaceAccessGrantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated team access grant
	TeamWorkspaceAccessGrant *TeamWorkspaceAccessGrant `protobuf:"bytes,1,opt,name=team_workspace_access_grant,json=teamWorkspaceAccessGrant,proto3" json:"team_workspace_access_grant,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateTeamWorkspaceAccessGrantResponse) Reset() {
	*x = UpdateTeamWorkspaceAccessGrantResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamWorkspaceAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamWorkspaceAccessGrantResponse) ProtoMessage() {}

func (x *UpdateTeamWorkspaceAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamWorkspaceAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamWorkspaceAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTeamWorkspaceAccessGrantResponse) GetTeamWorkspaceAccessGrant() *TeamWorkspaceAccessGrant {
	if x != nil {
		return x.TeamWorkspaceAccessGrant
	}
	return nil
}

type DeleteTeamWorkspaceAccessGrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the team to whose access grant should be deleted
	TeamId string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// The ID of the workspace whose access grant should be deleted
	WorkspaceId   string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamWorkspaceAccessGrantRequest) Reset() {
	*x = DeleteTeamWorkspaceAccessGrantRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamWorkspaceAccessGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamWorkspaceAccessGrantRequest) ProtoMessage() {}

func (x *DeleteTeamWorkspaceAccessGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamWorkspaceAccessGrantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamWorkspaceAccessGrantRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTeamWorkspaceAccessGrantRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *DeleteTeamWorkspaceAccessGrantRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type DeleteTeamWorkspaceAccessGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamWorkspaceAccessGrantResponse) Reset() {
	*x = DeleteTeamWorkspaceAccessGrantResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamWorkspaceAccessGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamWorkspaceAccessGrantResponse) ProtoMessage() {}

func (x *DeleteTeamWorkspaceAccessGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamWorkspaceAccessGrantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamWorkspaceAccessGrantResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{10}
}

type DeleteTeamWorkspaceAccessGrantByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the team access grant
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamWorkspaceAccessGrantByIdRequest) Reset() {
	*x = DeleteTeamWorkspaceAccessGrantByIdRequest{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamWorkspaceAccessGrantByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamWorkspaceAccessGrantByIdRequest) ProtoMessage() {}

func (x *DeleteTeamWorkspaceAccessGrantByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamWorkspaceAccessGrantByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamWorkspaceAccessGrantByIdRequest) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTeamWorkspaceAccessGrantByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTeamWorkspaceAccessGrantByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamWorkspaceAccessGrantByIdResponse) Reset() {
	*x = DeleteTeamWorkspaceAccessGrantByIdResponse{}
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamWorkspaceAccessGrantByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamWorkspaceAccessGrantByIdResponse) ProtoMessage() {}

func (x *DeleteTeamWorkspaceAccessGrantByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamWorkspaceAccessGrantByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeamWorkspaceAccessGrantByIdResponse) Descriptor() ([]byte, []int) {
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP(), []int{12}
}

var File_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto protoreflect.FileDescriptor

const file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDesc = "" +
	"\n" +
	"Jterrabase/team_workspace_access_grant/v1/team_workspace_access_grant.proto\x12(terrabase.team_workspace_access_grant.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eterrabase/authz/v1/authz.proto\x1a4terrabase/team_access_type/v1/team_access_type.proto\"\xac\x02\n" +
	"\x18TeamWorkspaceAccessGrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12N\n" +
	"\vaccess_type\x18\x04 \x01(\x0e2-.terrabase.team_access_type.v1.TeamAccessTypeR\n" +
	"accessType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x01\n" +
	"%CreateTeamWorkspaceAccessGrantRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\x12S\n" +
	"\vaccess_type\x18\x03 \x01(\x0e2-.terrabase.team_access_type.v1.TeamAccessTypeB\x03\xe0A\x02R\n" +
	"accessType\"\xac\x01\n" +
	"&CreateTeamWorkspaceAccessGrantResponse\x12\x81\x01\n" +
	"\x1bteam_workspace_access_grant\x18\x01 \x01(\v2B.terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantR\x18teamWorkspaceAccessGrant\"9\n" +
	"\"GetTeamWorkspaceAccessGrantRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\xa9\x01\n" +
	"#GetTeamWorkspaceAccessGrantResponse\x12\x81\x01\n" +
	"\x1bteam_workspace_access_grant\x18\x01 \x01(\v2B.terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantR\x18teamWorkspaceAccessGrant\"\xec\x01\n" +
	"$ListTeamWorkspaceAccessGrantsRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tH\x00R\x06teamId\x88\x01\x01\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tH\x01R\vworkspaceId\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x02R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x03R\tpageToken\x88\x01\x01B\n" +
	"\n" +
	"\b_team_idB\x0f\n" +
	"\r_workspace_idB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xee\x01\n" +
	"%ListTeamWorkspaceAccessGrantsResponse\x12\x83\x01\n" +
	"\x1cteam_workspace_access_grants\x18\x01 \x03(\v2B.terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantR\x19teamWorkspaceAccessGrants\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\x91\x01\n" +
	"%UpdateTeamWorkspaceAccessGrantRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12S\n" +
	"\vaccess_type\x18\x02 \x01(\x0e2-.terrabase.team_access_type.v1.TeamAccessTypeB\x03\xe0A\x02R\n" +
	"accessType\"\xac\x01\n" +
	"&UpdateTeamWorkspaceAccessGrantResponse\x12\x81\x01\n" +
	"\x1bteam_workspace_access_grant\x18\x01 \x01(\v2B.terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantR\x18teamWorkspaceAccessGrant\"m\n" +
	"%DeleteTeamWorkspaceAccessGrantRequest\x12\x1c\n" +
	"\ateam_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x06teamId\x12&\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x03\xe0A\x02R\vworkspaceId\"(\n" +
	"&DeleteTeamWorkspaceAccessGrantResponse\"@\n" +
	")DeleteTeamWorkspaceAccessGrantByIdRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\",\n" +
	"*DeleteTeamWorkspaceAccessGrantByIdResponse2\x97\n" +
	"\n" +
	"\x1fTeamWorkspaceAccessGrantService\x12\xd0\x01\n" +
	"\x1eCreateTeamWorkspaceAccessGrant\x12O.terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantRequest\x1aP.terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\n" +
	"\x04\x12\xc9\x01\n" +
	"\x1bGetTeamWorkspaceAccessGrant\x12L.terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantRequest\x1aM.terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantResponse\"\r\x88\xb5\x18\x01\x92\xb5\x18\x05\x01\v\n" +
	"\x05\x04\x12\xcf\x01\n" +
	"\x1dListTeamWorkspaceAccessGrants\x12N.terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsRequest\x1aO.terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsResponse\"\r\x88\xb5\x18\x01\x92\xb5\x18\x05\x01\v\n" +
	"\x05\x04\x12\xd0\x01\n" +
	"\x1eUpdateTeamWorkspaceAccessGrant\x12O.terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantRequest\x1aP.terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\n" +
	"\x04\x12\xd0\x01\n" +
	"\x1eDeleteTeamWorkspaceAccessGrant\x12O.terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantRequest\x1aP.terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\n" +
	"\x04\x12\xdc\x01\n" +
	"\"DeleteTeamWorkspaceAccessGrantById\x12S.terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdRequest\x1aT.terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdResponse\"\v\x88\xb5\x18\x01\x92\xb5\x18\x03\x01\n" +
	"\x04BnZlgithub.com/terrabase-dev/terrabase/specs/terrabase/team_workspace_access_grant/v1;teamWorkspaceAccessGrantv1b\x06proto3"

var (
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescOnce sync.Once
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescData []byte
)

func file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescGZIP() []byte {
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescOnce.Do(func() {
		file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDesc), len(file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDesc)))
	})
	return file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDescData
}

var file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_goTypes = []any{
	(*TeamWorkspaceAccessGrant)(nil),                   // 0: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant
	(*CreateTeamWorkspaceAccessGrantRequest)(nil),      // 1: terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantRequest
	(*CreateTeamWorkspaceAccessGrantResponse)(nil),     // 2: terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantResponse
	(*GetTeamWorkspaceAccessGrantRequest)(nil),         // 3: terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantRequest
	(*GetTeamWorkspaceAccessGrantResponse)(nil),        // 4: terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantResponse
	(*ListTeamWorkspaceAccessGrantsRequest)(nil),       // 5: terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsRequest
	(*ListTeamWorkspaceAccessGrantsResponse)(nil),      // 6: terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsResponse
	(*UpdateTeamWorkspaceAccessGrantRequest)(nil),      // 7: terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantRequest
	(*UpdateTeamWorkspaceAccessGrantResponse)(nil),     // 8: terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantResponse
	(*DeleteTeamWorkspaceAccessGrantRequest)(nil),      // 9: terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantRequest
	(*DeleteTeamWorkspaceAccessGrantResponse)(nil),     // 10: terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantResponse
	(*DeleteTeamWorkspaceAccessGrantByIdRequest)(nil),  // 11: terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdRequest
	(*DeleteTeamWorkspaceAccessGrantByIdResponse)(nil), // 12: terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdResponse
	(v1.TeamAccessType)(0),                             // 13: terrabase.team_access_type.v1.TeamAccessType
	(*timestamppb.Timestamp)(nil),                      // 14: google.protobuf.Timestamp
}
var file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_depIdxs = []int32{
	13, // 0: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant.access_type:type_name -> terrabase.team_access_type.v1.TeamAccessType
	14, // 1: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant.updated_at:type_name -> google.protobuf.Timestamp
	13, // 3: terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantRequest.access_type:type_name -> terrabase.team_access_type.v1.TeamAccessType
	0,  // 4: terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantResponse.team_workspace_access_grant:type_name -> terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant
	0,  // 5: terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantResponse.team_workspace_access_grant:type_name -> terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant
	0,  // 6: terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsResponse.team_workspace_access_grants:type_name -> terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant
	13, // 7: terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantRequest.access_type:type_name -> terrabase.team_access_type.v1.TeamAccessType
	0,  // 8: terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantResponse.team_workspace_access_grant:type_name -> terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrant
	1,  // 9: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.CreateTeamWorkspaceAccessGrant:input_type -> terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantRequest
	3,  // 10: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.GetTeamWorkspaceAccessGrant:input_type -> terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantRequest
	5,  // 11: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.ListTeamWorkspaceAccessGrants:input_type -> terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsRequest
	7,  // 12: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.UpdateTeamWorkspaceAccessGrant:input_type -> terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantRequest
	9,  // 13: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.DeleteTeamWorkspaceAccessGrant:input_type -> terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantRequest
	11, // 14: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.DeleteTeamWorkspaceAccessGrantById:input_type -> terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdRequest
	2,  // 15: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.CreateTeamWorkspaceAccessGrant:output_type -> terrabase.team_workspace_access_grant.v1.CreateTeamWorkspaceAccessGrantResponse
	4,  // 16: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.GetTeamWorkspaceAccessGrant:output_type -> terrabase.team_workspace_access_grant.v1.GetTeamWorkspaceAccessGrantResponse
	6,  // 17: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.ListTeamWorkspaceAccessGrants:output_type -> terrabase.team_workspace_access_grant.v1.ListTeamWorkspaceAccessGrantsResponse
	8,  // 18: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.UpdateTeamWorkspaceAccessGrant:output_type -> terrabase.team_workspace_access_grant.v1.UpdateTeamWorkspaceAccessGrantResponse
	10, // 19: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.DeleteTeamWorkspaceAccessGrant:output_type -> terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantResponse
	12, // 20: terrabase.team_workspace_access_grant.v1.TeamWorkspaceAccessGrantService.DeleteTeamWorkspaceAccessGrantById:output_type -> terrabase.team_workspace_access_grant.v1.DeleteTeamWorkspaceAccessGrantByIdResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_init() }
func file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_init() {
	if File_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto != nil {
		return
	}
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[5].OneofWrappers = []any{}
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDesc), len(file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_goTypes,
		DependencyIndexes: file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_depIdxs,
		MessageInfos:      file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_msgTypes,
	}.Build()
	File_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto = out.File
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_goTypes = nil
	file_terrabase_team_workspace_access_grant_v1_team_workspace_access_grant_proto_depIdxs = nil
}
