# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrabase.workspace.v1 import workspace_pb2 as terrabase_dot_workspace_dot_v1_dot_workspace__pb2


class WorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkspace = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/CreateWorkspace',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetWorkspace = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/GetWorkspace',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceResponse.FromString,
                _registered_method=True)
        self.ListWorkspaces = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/ListWorkspaces',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesResponse.FromString,
                _registered_method=True)
        self.UpdateWorkspace = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/UpdateWorkspace',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceResponse.FromString,
                _registered_method=True)
        self.DeleteWorkspace = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/DeleteWorkspace',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceResponse.FromString,
                _registered_method=True)
        self.GrantTeamAccess = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/GrantTeamAccess',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessResponse.FromString,
                _registered_method=True)
        self.RevokeTeamAccess = channel.unary_unary(
                '/terrabase.workspace.v1.WorkspaceService/RevokeTeamAccess',
                request_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessRequest.SerializeToString,
                response_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessResponse.FromString,
                _registered_method=True)


class WorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantTeamAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeTeamAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceResponse.SerializeToString,
            ),
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesResponse.SerializeToString,
            ),
            'UpdateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkspace,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceResponse.SerializeToString,
            ),
            'DeleteWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkspace,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceResponse.SerializeToString,
            ),
            'GrantTeamAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantTeamAccess,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessResponse.SerializeToString,
            ),
            'RevokeTeamAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeTeamAccess,
                    request_deserializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessRequest.FromString,
                    response_serializer=terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terrabase.workspace.v1.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terrabase.workspace.v1.WorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/CreateWorkspace',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/GetWorkspace',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GetWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/ListWorkspaces',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.ListWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/UpdateWorkspace',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.UpdateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/DeleteWorkspace',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.DeleteWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantTeamAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/GrantTeamAccess',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.GrantTeamAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeTeamAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.workspace.v1.WorkspaceService/RevokeTeamAccess',
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessRequest.SerializeToString,
            terrabase_dot_workspace_dot_v1_dot_workspace__pb2.RevokeTeamAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
