# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrabase.team.v1 import team_pb2 as terrabase_dot_team_dot_v1_dot_team__pb2


class TeamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTeam = channel.unary_unary(
                '/terrabase.team.v1.TeamService/CreateTeam',
                request_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamRequest.SerializeToString,
                response_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamResponse.FromString,
                _registered_method=True)
        self.GetTeam = channel.unary_unary(
                '/terrabase.team.v1.TeamService/GetTeam',
                request_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamRequest.SerializeToString,
                response_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamResponse.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_unary(
                '/terrabase.team.v1.TeamService/ListTeams',
                request_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsResponse.FromString,
                _registered_method=True)
        self.UpdateTeam = channel.unary_unary(
                '/terrabase.team.v1.TeamService/UpdateTeam',
                request_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamRequest.SerializeToString,
                response_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamResponse.FromString,
                _registered_method=True)
        self.DeleteTeam = channel.unary_unary(
                '/terrabase.team.v1.TeamService/DeleteTeam',
                request_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamRequest.SerializeToString,
                response_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamResponse.FromString,
                _registered_method=True)


class TeamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTeam,
                    request_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamRequest.FromString,
                    response_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamResponse.SerializeToString,
            ),
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamRequest.FromString,
                    response_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamResponse.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsRequest.FromString,
                    response_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsResponse.SerializeToString,
            ),
            'UpdateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTeam,
                    request_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamRequest.FromString,
                    response_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamResponse.SerializeToString,
            ),
            'DeleteTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTeam,
                    request_deserializer=terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamRequest.FromString,
                    response_serializer=terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terrabase.team.v1.TeamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terrabase.team.v1.TeamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.team.v1.TeamService/CreateTeam',
            terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamRequest.SerializeToString,
            terrabase_dot_team_dot_v1_dot_team__pb2.CreateTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.team.v1.TeamService/GetTeam',
            terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamRequest.SerializeToString,
            terrabase_dot_team_dot_v1_dot_team__pb2.GetTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.team.v1.TeamService/ListTeams',
            terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsRequest.SerializeToString,
            terrabase_dot_team_dot_v1_dot_team__pb2.ListTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.team.v1.TeamService/UpdateTeam',
            terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamRequest.SerializeToString,
            terrabase_dot_team_dot_v1_dot_team__pb2.UpdateTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.team.v1.TeamService/DeleteTeam',
            terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamRequest.SerializeToString,
            terrabase_dot_team_dot_v1_dot_team__pb2.DeleteTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
