# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrabase.environment.v1 import environment_pb2 as terrabase_dot_environment_dot_v1_dot_environment__pb2


class EnvironmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/terrabase.environment.v1.EnvironmentService/CreateEnvironment',
                request_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
                _registered_method=True)
        self.GetEnvironment = channel.unary_unary(
                '/terrabase.environment.v1.EnvironmentService/GetEnvironment',
                request_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentResponse.FromString,
                _registered_method=True)
        self.ListEnvironments = channel.unary_unary(
                '/terrabase.environment.v1.EnvironmentService/ListEnvironments',
                request_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsRequest.SerializeToString,
                response_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsResponse.FromString,
                _registered_method=True)
        self.UpdateEnvironment = channel.unary_unary(
                '/terrabase.environment.v1.EnvironmentService/UpdateEnvironment',
                request_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentRequest.SerializeToString,
                response_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentResponse.FromString,
                _registered_method=True)
        self.DeleteEnvironment = channel.unary_unary(
                '/terrabase.environment.v1.EnvironmentService/DeleteEnvironment',
                request_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentResponse.FromString,
                _registered_method=True)


class EnvironmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentResponse.SerializeToString,
            ),
            'ListEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEnvironments,
                    request_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsRequest.FromString,
                    response_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsResponse.SerializeToString,
            ),
            'UpdateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnvironment,
                    request_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentRequest.FromString,
                    response_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentResponse.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terrabase.environment.v1.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terrabase.environment.v1.EnvironmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.environment.v1.EnvironmentService/CreateEnvironment',
            terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentRequest.SerializeToString,
            terrabase_dot_environment_dot_v1_dot_environment__pb2.CreateEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.environment.v1.EnvironmentService/GetEnvironment',
            terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentRequest.SerializeToString,
            terrabase_dot_environment_dot_v1_dot_environment__pb2.GetEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.environment.v1.EnvironmentService/ListEnvironments',
            terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsRequest.SerializeToString,
            terrabase_dot_environment_dot_v1_dot_environment__pb2.ListEnvironmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.environment.v1.EnvironmentService/UpdateEnvironment',
            terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentRequest.SerializeToString,
            terrabase_dot_environment_dot_v1_dot_environment__pb2.UpdateEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terrabase.environment.v1.EnvironmentService/DeleteEnvironment',
            terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentRequest.SerializeToString,
            terrabase_dot_environment_dot_v1_dot_environment__pb2.DeleteEnvironmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
